name: Docker Build and Release
on: [push]
env:
  #### An dieser Stelle müssen eure persönlichen Umgebungsvariablen eingetragen werden
  # Tip: Die Token/der API-Key werden als Secrets in den Repository-Settings eingetragen und hier referenziert.
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  GITHUB_ACCESSTOKEN: ${{ secrets.GITHUB_ACCESSTOKEN }}
jobs:
  compile:
    name: Compile
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11
          cache: maven
      #### AUFGABE 2: SONAR
        # hier ist der Platz für die Konfiguration der Sonar Analyse
      
      - name: Maven Compile
        run: |
          mvn package

      - name: Docker Build
        run: |
          docker build --tag ghcr.io/kerim2014/pet-clinic:latest -f Dockerfile .

      - name: Docker Login
        run: |
          echo $GITHUB_ACCESSTOKEN | docker login ghcr.io -u kerim2014 --password-stdin

      - name: Docker Push
        run: |
          docker push ghcr.io/kerim2014/pet-clinic:latest
